### ISSUE TITLE
README.md - "Project Page" section - "Vertical Navigation with jQuery" link 404 error

### ISSUE THREAD

**Issue by phillyjeep** [sebastiansulinski/jquery-vertical-navigation#1]
README.md - "Project Page" section - "Vertical Navigation with jQuery" link for url http://sebastiansulinski.github.io/jquery-vertical-navigation results in 404 error

**Comment by sebastiansulinski** [comment]
Thanks for pointing this out @phillyjeep - I've now removed it from the readme.
